### PR TITLE
Task humour

### PR DESCRIPTION
**Pull request by thomas065**
This task is not complete, just submitting for reference and JS help

### CODE REVIEW

**Review by kristenking — APPROVED** [review]
we met with Thomas and discussed how existing PR can be improved and refactored by mapping through the daily pics. Approving with the anticipation that discussed changes will be implemented before merging.

**Review by vmaineng — COMMENTED** [review]
I'm excited for concurrently! Thanks for implementing the changes!

Does humor.js need to be in brackets? I'm thinking it should be because it is a dynamic end point? Thoughts?

**Review by vmaineng — APPROVED** [review]
Thomas and I talked and he mentioned the dynamic end point is located in Todaypic.js Thanks for clarifying up my question!

**Comment by thomas065** [comment]
I fixed a major parsing error in the eslintrc.json that was causing a babel conflict by first commenting out the original object and then replacing it with:

 {
  "extends": ["next/babel","next/core-web-vitals"]
}

This immediately removed the error.

**Review by kristenking — COMMENTED** [review]
Thank you Thomas for fixing environment issues. Looks like branch is ready to be merged after resolving all conflicts. Please let us know if you need any support with that.

**Pull request merged**
