### PR TITLE
added Back button

### PR DESCRIPTION
**Pull request by thomas065**
added Back button to Humour section

### CODE REVIEW

**Review by vmaineng — APPROVED** [review]
Thanks for adding in the ArrowForwardIcon!

**Review by kristenking — COMMENTED** [review]
Thank you, Thomas! If we foresee using back button in other components/pages, I would recommend to put back button in a separate component and import it. Lmk what you think.

**Comment by thomas065** [comment]
Imported Back Button as a component for reusability.

**Comment by thomas065** [comment]
removed and imported Back Button as reusable component to the Videos section.

**Comment by thomas065** [comment]
moved the Back button component to a new Helpers folder

**Review by kristenking — APPROVED** [review]
Thank you for addressing concerns and cleaning up some syntax, Thomas! Makes eye happy to see the component has been used twice in separate pages of the project already.

**Pull request merged**
